============================= test session starts ==============================
platform darwin -- Python 2.7.13, pytest-3.2.1, py-1.4.34, pluggy-0.4.0
rootdir: /Users/timothyhochberg/Documents/SkyTruth/Code/encounters, inifile:
collected 3 items / 1 errors

==================================== ERRORS ====================================
_______ ERROR collecting pipeline/transforms/test_compute_encounters.py ________
//anaconda/envs/dataflow/lib/python2.7/site-packages/_pytest/python.py:395: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
//anaconda/envs/dataflow/lib/python2.7/site-packages/py/_path/local.py:662: in pyimport
    __import__(modname)
E     File "/Users/timothyhochberg/Documents/SkyTruth/Code/encounters/pipeline/transforms/test_compute_encounters.py", line 157
E       datetime.datetime(2015, 3, 19, 7, 40, tzinfo=<UTC>), 'mean_longitude': 38.53450050638802,
E                                                    ^
E   SyntaxError: invalid syntax
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.48 seconds ============================
